# Root logger option
log4j.rootLogger=DEBUG, CONSOLE, FILE

# File appender for general logging
log4j.appender.FILE=org.apache.log4j.FileAppender
log4j.appender.FILE.File=core_java/jdbc/src/main/resources/logs/app.log
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5p %c{1} - %m%n

# File appender for error logging
log4j.appender.ERROR_FILE=org.apache.log4j.FileAppender
log4j.appender.ERROR_FILE.File=/core_java/jdbc/src/main/resources/logs/error.log
log4j.appender.ERROR_FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.ERROR_FILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5p %c{1} - %m%n
log4j.appender.ERROR_FILE.Threshold=ERROR